Ported Dockerfile to rockcraft.yaml to start building ROCKs
Signed-off-by: utkarshbhatthere <utkarsh.bhatt@canonical.com>

diff --git a/.github/workflows/build_and_test.yaml b/.github/workflows/build_and_test.yaml
--- a/.github/workflows/build_and_test.yaml
+++ b/.github/workflows/build_and_test.yaml
@@ -12,34 +12,24 @@ defaults:
     shell: bash --noprofile --norc -eo pipefail -x {0}
 
 jobs:
-  build:
+  build-rock:
     runs-on: ubuntu-latest
+    outputs:
+      rock: ${{ steps.rockcraft.outputs.rock }}
     steps:
-      -
-        name: Checkout
+      - name: Checkout repository
         uses: actions/checkout@v3
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      -
-        name: Build and export
-        uses: docker/build-push-action@v3
+      - name: Prepare Rock
+        uses: canonical/craft-actions/rockcraft-pack@main
+        id: rockcraft
+      - uses: actions/upload-artifact@v3
         with:
-          context: .
-          tags: canonical/ceph:latest
-          outputs: type=docker,dest=/tmp/myimage.tar
-          build-args: |
-            "CUSTOM_APT_REPO=ppa:peter-sabaini/ceph-test"
-      -
-        name: Upload artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: myimage
-          path: /tmp/myimage.tar
+          name: rock
+          path: ${{ steps.rockcraft.outputs.rock }}
 
   CephAdmScriptTest:
     runs-on: ubuntu-latest
-    needs: build
+    needs: build-rock
     strategy:
       matrix:
         python-version: ["3.10"]
@@ -57,8 +47,7 @@ jobs:
       - name: Download artifact
         uses: actions/download-artifact@v3
         with:
-          name: myimage
-          path: /tmp
+          name: rock
 
       - name: set up python ${{ matrix.python-version }}
         uses: actions/setup-python@v4
@@ -67,6 +56,7 @@ jobs:
 
       - name: install dependencies
         run: |
+          sudo apt install skopeo
           sudo python -m pip install --upgrade pip
           sudo pip install flake8 pep8-naming pylxd pyyaml argparse
 
@@ -79,8 +69,10 @@ jobs:
 
       - name: Load image to registry
         run: |
+          ls
+          rock_file=$(ls *.rock | head -1)
           docker run -d -p 5000:5000 --restart=always --name registry registry:2
-          docker load --input /tmp/myimage.tar
+          skopeo --insecure-policy copy oci-archive:$rock_file docker-daemon:canonical/ceph:latest
           docker image ls -a
           docker image tag canonical/ceph:latest localhost:5000/canonical/ceph:latest
           sleep 10
@@ -93,7 +85,7 @@ jobs:
 
   CephAdmScriptLxdTest:
     runs-on: ubuntu-latest
-    needs: build
+    needs: build-rock
     strategy:
       matrix:
         python-version: ["3.10"]
@@ -111,8 +103,7 @@ jobs:
       - name: Download artifact
         uses: actions/download-artifact@v3
         with:
-          name: myimage
-          path: /tmp
+          name: rock
 
       - name: set up python ${{ matrix.python-version }}
         uses: actions/setup-python@v4
@@ -130,12 +121,15 @@ jobs:
 
       - name: Load image to registry
         run: |
+          ls
+          rock_file=$(ls *.rock | head -1)
           docker run -d -p 5000:5000 --restart=always --name registry registry:2
-          docker load --input /tmp/myimage.tar
+          skopeo --insecure-policy copy oci-archive:$rock_file docker-daemon:canonical/ceph:latest
           docker image ls -a
           docker image tag canonical/ceph:latest localhost:5000/canonical/ceph:latest
           sleep 10
           docker push localhost:5000/canonical/ceph
+          echo $'[registries.insecure]\nregistries = ["localhost:5000"]' | sudo tee -a /etc/containers/registries.conf
 
       - name: install and init lxd snap
         run: |
@@ -154,7 +148,7 @@ jobs:
           sudo python test/deploy.py --osd-num 0 --container 1 image "$reg_addr:5000/canonical/ceph:latest"
 
   RookTest:
-    needs: build
+    needs: build-rock
     runs-on: ubuntu-latest
 
     steps:
@@ -182,15 +176,17 @@ jobs:
       - name: Download artifact
         uses: actions/download-artifact@v3
         with:
-          name: myimage
-          path: /tmp
+          name: rock
 
       - name: Load image and load to registry
         run: |
+          ls
+          rock_file=$(ls *.rock | head -1)
           docker run -d -p 5000:5000 --restart=always --name registry registry:2
-          docker load --input /tmp/myimage.tar
+          skopeo --insecure-policy copy oci-archive:$rock_file docker-daemon:canonical/ceph:latest
           docker image ls -a
           docker image tag canonical/ceph:latest localhost:5000/canonical/ceph:latest
+          sleep 10
           docker push localhost:5000/canonical/ceph
           echo $'[registries.insecure]\nregistries = ["localhost:5000"]' | sudo tee -a /etc/containers/registries.conf
 
@@ -237,17 +233,12 @@ jobs:
 
       - name: test subvolumegroup validation
         run: |
-          cd rook
-          toolbox=$(kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o jsonpath='{.items[*].metadata.name}')
-          # pass the correct subvolumegroup and cephfs_filesystem flag name
-          kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --subvolume-group group-a --cephfs-filesystem-name myfs
-          # pass the wrong subvolumegroup name
-          if output=$(kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --subvolume-group false-test-subvolume-group); then
-            echo "unexpectedly succeeded after passing the wrong subvolumegroup name: $output"
-            exit 1
-          else
-            echo "script failed because wrong subvolumegroup name was passed"
-          fi
+            cd rook
+            toolbox=$(kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o jsonpath='{.items[*].metadata.name}')
+            # pass the correct subvolumegroup and cephfs_filesystem flag name
+            kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --subvolume-group group-a --cephfs-filesystem-name myfs
+            # pass the subvolumegroup name which doesn't exist
+            kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --subvolume-group false-test-subvolume-group
 
       - name: test of rados namespace
         run: |
@@ -313,18 +304,42 @@ jobs:
           rgw_endpoint=$(kubectl get service -n rook-ceph |  awk '/rgw/ {print $3":80"}')
           toolbox=$(kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o jsonpath='{.items[*].metadata.name}')
           # pass the valid rgw-endpoint of same ceph cluster
-          timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint $rgw_endpoint; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"
+          timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint $rgw_endpoint 2> output.txt; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"
+          tests/scripts/github-action-helper.sh check_empty_file output.txt
+          rm -f output.txt
           # pass the invalid rgw-endpoint of different ceph cluster
-          if output=$(timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint 10.108.96.128:80; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"); then
-            echo "unexpectedly succeeded after passing the wrong rgw-endpoint: $output"
-            exit 1
+          timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint 10.108.96.128:80  2> output.txt; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"
+          if [ -s output.txt ]; then
+            echo "script run completed with stderr error after passing the wrong rgw-endpoint: $output"
+            rm -f output.txt
           else
-            echo "validation failed because wrong endpoint was provided"
+            echo "no stderr error even when wrong endpoint was provided"
+            rm -f output.txt
+            exit 1
           fi
           # pass the valid rgw-endpoint of same ceph cluster with --rgw-tls-cert-path
-          timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint $rgw_endpoint --rgw-tls-cert-path my-cert; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"
+          timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint $rgw_endpoint --rgw-tls-cert-path my-cert 2> output.txt; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"
+          tests/scripts/github-action-helper.sh check_empty_file output.txt
+          rm -f output.txt
           # pass the valid rgw-endpoint of same ceph cluster with --rgw-skip-tls
-          timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint $rgw_endpoint --rgw-skip-tls true; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"
+          timeout 15 sh -c "until kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-endpoint $rgw_endpoint --rgw-skip-tls true 2> output.txt; do sleep 1 && echo 'waiting for the rgw endpoint to be validated'; done"
+          tests/scripts/github-action-helper.sh check_empty_file output.txt
+          rm -f output.txt
+      
+      - name: validate multisite
+        run: |
+          cd rook
+          toolbox=$(kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o jsonpath='{.items[*].metadata.name}')
+          # create realm
+          kubectl -n rook-ceph exec $toolbox -- radosgw-admin realm create --rgw-realm=realm1
+          # pass correct realm
+          kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-realm-name realm1
+          # pass wrong realm
+          if output=$(kubectl -n rook-ceph exec $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool --rgw-realm-name realm3); then
+            echo "script run completed with stderr error after passing the wrong realm: $output"
+          else
+            echo "script failed because wrong realm was passed"
+          fi
 
       - name: test osd removal jobs
         run: ./scripts/test-osd-removal.sh
